### PR TITLE
Refactor questions on each Markdown document

### PR DESCRIPTION
**Pull request by corneliu-rotari**

### CODE REVIEW

**Review by mariasfiraiala — CHANGES_REQUESTED** [review]
Thanks @corneliu-rotari! I think it would look better if you added an extra `#` in front of every question, meaning that we'd have a smaller header (eg: `###3. Cine trimite un semnal unui proces?`).

I think it would make sense to have only one commit for these changes, so rebase the 5 existing ones into one. Please, sign-off your commit, afterwards. Take a look at the [contributing guidelines](https://github.com/mariasfiraiala/SO-exam/blob/master/CONTRIBUTING.md).

**Comment by corneliu-rotari** [comment]
That's it

**Comment by corneliu-rotari** [comment]
For the future we can consider to add a dropdown for the question.
```
<details>
     <summary>
         <h3>          
             Question?
         </h3>
      </summary>

      Answer
</details>
```
<details>
     <summary>
         <h2>          
             Question?
         </h2>
      </summary>

      Answer
</details>

**Comment by mariasfiraiala** [comment]
> For the future we can consider to add a dropdown for the question.

I already thought of that, however in another context: I'd like to add longer responses to the questions and hide them (with a dropdown) as to not overwhelm students with too much details. Thanks for the idea!!!

**Review by mariasfiraiala — APPROVED** [review]
Looks great, thank you @corneliu-rotari!

**Pull request merged**
